name: Comment on the pull request

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Receive Pull Request"]
    types:
      - completed

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"

  test-pr:
    name: "Test if pull request is valid"
    runs-on: ubuntu-latest
    if: >
      ${{ github.event.workflow_run.event == 'pull_request' &&
      github.event.workflow_run.conclusion == 'success' }}
    outputs:
      is_valid: ${{ steps.check-pr.outputs.VALID }}
      payload: ${{ steps.check-pr.outputs.payload }}
      number: ${{ steps.get-pr.outputs.NUM }}
    steps:
      - name: 'Download PR artifact'
        uses: zkamvar/actions/download-workflow-artifact@main
        with:
          run: ${{ github.event.workflow_run.id }}
          dir: ${{ github.workspace }}
          repo: ${{ github.repository }}
          name: 'pr'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get PR Number"
        id: get-pr
        run: |
          unzip pr.zip
          echo "::set-output name=NUM::$(cat ./NR)"
      
      - name: "Check PR"
        id: check-pr
        uses: zkamvar/actions/check-valid-pr@main
        with:
          pr: ${{ steps.get-pr.outputs.NUM }}
          sha: ${{ github.events.workflow_run.head_commit.sha }}
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
  show-outputs:
    name: "Show Outputs"
    runs-on: ubuntu-latest
    needs: test-pr
    steps:
      - run: |
          echo ${{ needs.test-pr.outputs.is_valid }}
          echo ${{ needs.test-pr.outputs.number }}
          echo ${{ needs.test-pr.outputs.payload }}

  create-branch:
    name: "Create Git Branch"
    needs: test-pr
    runs-on: ubuntu-latest
    if: ${{ needs.test-pr.outputs.is_valid == 'true' }}
    env:
      NR: ${{ needs.test-pr.outputs.number }}
    steps:
      - name: 'Checkout md outputs'
        uses: actions/checkout@v2.3.4
        with:
          ref: md-outputs
          path: built
          fetch-depth: 1

      - name: 'Download built markdown'
        uses: zkamvar/actions/download-workflow-artifact@main
        with:
          run: ${{ github.event.workflow_run.id }}
          dir: ${{ github.workspace }}
          repo: ${{ github.repository }}
          name: 'built'
          token: ${{ secrets.GITHUB_TOKEN }}

      - run: unzip built.zip

      - name: "Create orphan and push"
        run: |
          cd built/
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          CURR_HEAD=$(git rev-parse HEAD)
          git checkout --orphan md-outputs-PR-${NR}
          git add -A 
          git commit -m "source commit: ${CURR_HEAD}"
          cd ..
          ls -d -A built/* | grep -v '.git' | xargs rm -r
          unzip -d built built.zip
          cd built
          git add -A
          git commit --allow-empty -m "differences for PR #${NR}"
          git push -u --force --set-upstream origin md-outputs-PR-${NR}

  comment-pr:
    name: "Comment on Pull Request"
    needs: [test-pr, create-branch]
    runs-on: ubuntu-latest
    if: ${{ needs.test-pr.outputs.is_valid == 'true' }}
    env:
      NR: ${{ needs.test-pr.outputs.number }}
    steps:
      - name: 'Download comment artifact'
        uses: zkamvar/actions/download-workflow-artifact@main
        with:
          run: ${{ github.event.workflow_run.id }}
          dir: ${{ github.workspace }}
          repo: ${{ github.repository }}
          name: 'diff'
          token: ${{ secrets.GITHUB_TOKEN }}

      - name: "Get message body"
        id: get-body
        run: |
          unzip diff.zip
          echo "::set-output name=BODY::$(cat ./diff.md)"

      - name: "Comment on PR"
        id: comment-diff
        uses: zkamvar/actions/comment-diff@main
        with:
          pr: ${{ env.NR }} 
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: ${{ steps.get-body.outputs.BODY}}

  comment-changed-workflow:
    name: "Comment Changed Workflow"
    needs: test-pr
    runs-on: ubuntu-latest
    if: >
      ${{ needs.test-pr.outputs.is_valid == 'false' &&
      needs.test-pr.outputs.payload }}
    env:
      NR: ${{ needs.test-pr.outputs.number }}
    steps:
      - name: "Comment on PR"
        id: comment-diff
        uses: zkamvar/actions/comment-diff@main
        with:
          pr: ${{ env.NR }} 
          repo: ${{ github.repository }}
          token: ${{ secrets.GITHUB_TOKEN }}
          body: "Pull Request contains modified workflows; no preview will be created."
   
