name: Echo PR

# read-write repo token
# access to secrets
on:
  workflow_run:
    workflows: ["Receive Pull Request"]
    types: '*'

jobs:
  shout:
    name: "Shout"
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
