name: "Close Pull Request Signal"

on:
  pull_request:
    types:
      [closed]

jobs:
  send-close-signal:
    name: "Send closing signal"
    runs-on: ubuntu-latest
    if: ${{ github.event.action == 'closed' }}
    steps:
      - name: "Create PRtifact"
        run: echo md-outputs-PR-${{ github.event.number }} > ./NR
      - name: Upload Diff
        uses: actions/upload-artifact@v2
        with:
          name: NR
          path: ./NR

