name: "Check for actions modification"

on:
  pull_request:
    types:
      [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Check out PR
        uses: actions/checkout@v2
      - name: Query Files Changed
        run: |
          git diff --staged --name-only | grep '^.github'
          if [[ $(git diff --staged --name-only | grep -c '^.github') -ne 0 ]]; then
            echo '::error .github files must not be modified'
            exit 1
          else
            exit 0
          fi
          
