on:
  pull_request:

name: "Receive Pull Request"

jobs:
  build-md-source:
    runs-on: macOS-latest
    env:
      GITHUB_PAT: ${{ secrets.GITHUB_TOKEN }}
      CHIVE: ${{ github.workspace }}/site/chive
      MD: ${{ github.workspace }}/site/built
    steps:
      - uses: actions/checkout@v2
      - name: Dump GitHub context
        env:
          GITHUB_CONTEXT: ${{ toJson(github) }}
        run: echo "$GITHUB_CONTEXT" > Rtifact

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: PR-tifact
          path: ${{ github.workspace }}/Rtifact

      - uses: r-lib/actions/setup-r@v1

      - uses: r-lib/actions/setup-pandoc@v1
        with:
          pandoc-version: "2.10"

      - name: Query dependencies
        run: |
          install.packages('remotes')
          install.packages('drat')
          drat:::add('zkamvar')
          saveRDS(remotes::package_deps('sandpaper', dependencies = TRUE), ".github/depends.Rds", version = 2)
          writeLines(sprintf("R-%i.%i", getRversion()$major, getRversion()$minor), ".github/R-version")
        shell: Rscript {0}

      - name: Cache R packages
        uses: actions/cache@v2
        with:
          path: ${{ env.R_LIBS_USER }}
          key: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-${{ hashFiles('.github/depends.Rds') }}
          restore-keys: ${{ runner.os }}-${{ hashFiles('.github/R-version') }}-1-

      - name: Install dependencies
        run: |
          remotes::install_github('carpentries/sandpaper', dependencies = TRUE)
        shell: Rscript {0}

      - name: Fetch Rendred Markdown
        run: |
          git clone --depth 1 -b md-sources ${{ github.event.repository.git_url }} "$MD"
      - name: Generate Diff
        run: |
          git config --local user.email "actions@github.com"
          git config --local user.name "GitHub Actions"
          Rscript -e 'sandpaper::build_lesson()'
          mkdir -p "$CHIVE"
          cd site/built
          echo "### Rendered Changes\n\n```diff\n" > "${CHIVE}/diff.md"
          git diff --summary > "${CHIVE}/diff.md"
          echo "\n```\n\n<details><summary>Full Diff</summary>\n\n" >> "${CHIVE}/diff.md"
          git diff --oneline >> "${CHIVE}/diff.md"
          echo "\n```\n\n</details>" >> "${CHIVE}/diff.md"

      - name: Upload Artifact
        uses: actions/upload-artifact@v2
        with:
          name: diff
          path: "${CHIVE}"

      - name: Teardown
        run: sandpaper::clear_site()
        shell: Rscript {0}
