name: "Check for actions modification"

on:
  pull_request:
    types:
      [opened, synchronize, reopened]

jobs:
  test:
    runs-on: ubuntu-latest
    steps:
      - name: Print github context
        env:
          GITHUB_CONTEXT: ${{ toJSON(github) }}
        run: echo "$GITHUB_CONTEXT"
      - name: Query Files Changed
        run: |
          if [[ $(git status --staged --names-only | grep '^.github') -ne 0 ]]; then
            echo '::error .github files must not be modified'
            exit 1
          else
            exit 0
          fi
          
